### ISSUE TITLE
Ask A Question option always included in the submit dropdown.

### ISSUE THREAD

**Issue by lots0logs** [psychobunny/nodebb-plugin-question-and-answer#3]
Maybe this is the intended behavior or perhaps its because I am an admin? The Ask A Question option is always available in the submit dropdown even for creating normal posts. Shouldnt it only show in the menu when a new topic is being created?

**Comment by psychobunny** [comment]
Fixed in 0b3931209066c960107bb734a4266d5c61a229cc
