### ISSUE TITLE
Topic owner/creator should be able to mark question as solved

### ISSUE THREAD

**Issue by lots0logs** [psychobunny/nodebb-plugin-question-and-answer#4]
The option for marking a question as solved is not presented to the user who created the topic. Currently only moderators and admins see the option. @psychobunny, any idea how I can fix this?

**Comment by lots0logs** [comment]
@psychobunny, as soon as you have a minute or two to spare, would you mind pointing me in the right direction so I can fix this on our forum? I would really appreciate it! Thanks. :smile:

**Comment by psychobunny** [comment]
I think I fixed this in Persona: https://github.com/NodeBB/nodebb-theme-persona/commit/3a148c29162e465cd04267e402a4befccec18b83

Seems like I forgot to backport it to vanilla/lavender, are you using either of those themes?

**Comment by psychobunny** [comment]
Looks like I did fix it in vanilla as well (lavender inherits this change): https://github.com/NodeBB/nodebb-theme-vanilla/commit/2e2216528c2bbd6a8982fb87e344063d26686e66

Are you running an older version of the theme perhaps?

**Comment by psychobunny** [comment]
You know what, I'm going crazy. I read the OP wrong, totally different issue. I'll have a look :)

**Comment by lots0logs** [comment]
I'm using a forked version of lavender. I have been backporting changes made to lavender so I don't think its an issue with my custom theme but perhaps I missed something. Let me know what you find. Thanks!!

**Comment by psychobunny** [comment]
fixed in https://github.com/NodeBB/nodebb-theme-vanilla/commit/065405f9a2205e1778de1486c4dc93c5cde4caff
