### ISSUE TITLE
[BUG] Bug with some 'unsolved' questions are not shown on /unsolved page

### ISSUE THREAD

**Issue by jtsimoes** [psychobunny/nodebb-plugin-question-and-answer#52]
I discovered that when you post a topic on a category that automatically creates a question instead of a normal topic (previously chosen on the ACP plugin page), that question will not show up on /unsolved page, **unless you make it as a normal topic and then ask as question again**... Only that way it will be shown on /unsolved.

I found it completely unintentionally, but yeah... I think it is a serious fault.
I hope I expressed myself well and I hope you can fix it!
Thanks.

**Comment by barisusakli** [comment]
what version of the plugin?

**Comment by jtsimoes** [comment]
@barisusakli Latest (v0.3.2)

**Comment by barisusakli** [comment]
0.3.4 is latest

**Comment by jtsimoes** [comment]
Oh... Okay, this is weird...
![image](https://user-images.githubusercontent.com/34691647/51956033-06abb780-243e-11e9-855a-2b66542d35cd.png)
