### ISSUE TITLE
Mark as Solved permissions?

### ISSUE THREAD

**Issue by pqvst** [psychobunny/nodebb-plugin-question-and-answer#6]
Who is able to mark questions as solved? Is it only admins?

**Comment by amarinelli** [comment]
The topic creator as well as admins are given control or marking solved or other actions.  Users just reading the topic won't see the _TOPIC TOOLS_ button which contains these actions.

Also, users who are given privileges (_Moderate_) to a certain category will have these actions.  Set category privileges in the admin panel (EDIT a category).

**Comment by psychobunny** [comment]
thanks @amarinelli
