### ISSUE TITLE
Cannot mark topic as solved or switch topic type

### ISSUE THREAD

**Issue by amarinelli** [psychobunny/nodebb-plugin-question-and-answer#9]
In both my current implementation of NodeBB (v0.8.1) and the NodeBB community, there are a few issues with this plugin for marking topics as solved or marking questions as normal topics, etc.

Chrome console is showing this error:

`Uncaught TypeError: ajaxify.variables.get is not a function` _nodebb.min.js:13_

**Comment by amarinelli** [comment]
I can help confirm that this was fixed with https://github.com/psychobunny/nodebb-plugin-question-and-answer/commit/ca7c4c0c06a97c673f86c40810fda51141b2456c

**Comment by psychobunny** [comment]
thanks :+1:
